### ISSUE TITLE
TCP Connection

### ISSUE THREAD

**Issue by TorbenLammers** [MathiasMeuleman/SIRS_Project_A33#12]
setting up a tcp connection between the VMs

**Comment by TorbenLammers** [comment]
if it is a python script we could use this 
https://stackoverflow.com/questions/10097491/call-and-receive-output-from-python-script-in-java

**Comment by Robert-OP** [comment]
The TCP connection is made using sockets, implemented in java as 2 different client-server classes.

**Comment by Robert-OP** [comment]
Pushed it to git under 2 classes (need them to run separate):
Server - SHD
Client - GW
