### ISSUE TITLE
Switch from ECB to CBC

### ISSUE THREAD

**Issue by MathiasMeuleman** [MathiasMeuleman/SIRS_Project_A33#18]
In Cryptography class. Needs some smart IV

**Comment by TorbenLammers** [comment]
Do wen really need to change this?

**Comment by TorbenLammers** [comment]
research needs to be done for this!:
- what are the problems if we use ECB mode and do we solve these problems by inputting timestamps for example?

**Comment by TorbenLammers** [comment]
we have to implement CBC. see report notes
