### ISSUE TITLE
Web server interface

### ISSUE THREAD

**Issue by TorbenLammers** [MathiasMeuleman/SIRS_Project_A33#24]
- input apriori shared in the gateway during runtime for adding new SHD
- should be done through the interface of the webserver
- interfcae of webserver should offer two options like "adding new SHD" -> "input apriori key" 
- 2. option "get current state of SHDs"

- maybe button for light bulb to switch on/off
- access to the persistant file storage of SHD states/data through web-interface?

**Comment by Robert-OP** [comment]
We need to think about the connection between the web server and java application first.

**Comment by Robert-OP** [comment]
Plan B: Do web interface in Intellij next to project.
