### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by TorbenLammers** [MathiasMeuleman/SIRS_Project_A33#7]
should run on the router as a VM

**Comment by Robert-OP** [comment]
Protect against DoS attacks

**Comment by Robert-OP** [comment]
1. Setup VM - router 
2. Connect other 2 VM
3. Test connection 
4. Build firewall
5. Test firewall

**Comment by Robert-OP** [comment]
Plan B: Create firewall file with necessary exceptions and explain it in the report/presentation.

**Comment by Robert-OP** [comment]
The firewall has not  been tested. It was only created and the rules regarding DoS attack  have been made. It has been added in the project under /firewall directory.
